-- MySQL Script generated by MySQL Workbench
-- Thu Dec 11 02:45:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assistencia_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assistencia_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assistencia_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assistencia_bd` ;

-- -----------------------------------------------------
-- Table `assistencia_bd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`clientes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assistencia_bd`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`equipamentos` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(50) NOT NULL,
  `defeito_relatado` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equip_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_equip_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `assistencia_bd`.`clientes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assistencia_bd`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`tecnicos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `especialidade` VARCHAR(80) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assistencia_bd`.`ordens_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`ordens_servico` (
  `id` INT NOT NULL,
  `equipamento_id` INT NOT NULL,
  `tecnico_id` INT NOT NULL,
  `data_abertura` DATE NOT NULL,
  `status` VARCHAR(40) NOT NULL,
  `valor_orcamento` DOUBLE NULL DEFAULT NULL,
  `valor_final` DOUBLE NULL DEFAULT NULL,
  `observacoes` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_os_equip_idx` (`equipamento_id` ASC) VISIBLE,
  INDEX `fk_os_tec_idx` (`tecnico_id` ASC) VISIBLE,
  CONSTRAINT `fk_os_equip`
    FOREIGN KEY (`equipamento_id`)
    REFERENCES `assistencia_bd`.`equipamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_os_tec`
    FOREIGN KEY (`tecnico_id`)
    REFERENCES `assistencia_bd`.`tecnicos` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assistencia_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`tipo_usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `modulo_admin` VARCHAR(1) NOT NULL,
  `modulo_atendimento` VARCHAR(1) NOT NULL,
  `modulo_tecnico` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assistencia_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assistencia_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipo_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `assistencia_bd`.`tipo_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `assistencia_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `assistencia_bd`;
INSERT INTO `assistencia_bd`.`tipo_usuario` (`id`, `nome`, `modulo_admin`, `modulo_atendimento`, `modulo_tecnico`) VALUES (1024, 'admin', 'S', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `assistencia_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `assistencia_bd`;
INSERT INTO `assistencia_bd`.`usuarios` (`id`, `nome`, `senha`, `tipo_usuario_id`) VALUES (1024, 'admin', '6c29cf7c7dc8ed663ba3a7cf87ccb3e841feddb513d80407b7985892ba0b46fe', 1024);

COMMIT;

