/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-12-08 14:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.app.adm;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Usuario;
import java.util.ArrayList;
import model.Usuario;
import model.TipoUsuario;

public final class usuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/home/app/modulos.jsp", Long.valueOf(1765202844301L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.TipoUsuario");
    _jspx_imports_classes.add("model.Usuario");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Usuários</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    ");
      out.write('\n');
      out.write('\n');
      out.write('\n');

    HttpSession s = request.getSession(false);

    Usuario usuarioLogado = null;
    TipoUsuario tipoUsuarioLogado = null;

    if (s != null) {
        usuarioLogado = (Usuario) s.getAttribute("usuario");
        tipoUsuarioLogado = (TipoUsuario) s.getAttribute("tipo_usuario");
    }

      out.write("\n");
      out.write("\n");
      out.write("<ul>\n");
      out.write("    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/menu.jsp\">Menu</a></li>\n");
      out.write("\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloAdmin())) { 
      out.write("\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/tipousuario.jsp\">Tipo Usuário</a></li>\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/usuarios.jsp\">Usuários</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloAtendimento())) { 
      out.write("\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/atendimento/clientes.jsp\">Clientes</a></li>\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/atendimento/equipamentos.jsp\">Equipamentos</a></li>\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/os/os.jsp\">Ordens de Serviço</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloTecnico())) { 
      out.write("\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/tecnicos/tecnicos.jsp\">Técnicos</a></li>\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/os/os.jsp\">OS Técnicas</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <li>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home?task=logout\">\n");
      out.write("            Logout ");
      out.print( usuarioLogado != null ? usuarioLogado.getNome() : "" );
      out.write("\n");
      out.write("        </a>\n");
      out.write("    </li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
 ArrayList<Usuario> dados = new Usuario().getAllTableEntities(); 
      out.write("\n");
      out.write("\n");
      out.write("    <h1>Usuários do Sistema</h1>\n");
      out.write("\n");
      out.write("    <table border=\"1\" cellpadding=\"5\">\n");
      out.write("        <tr>\n");
      out.write("            <th>ID</th>\n");
      out.write("            <th>Nome</th>\n");
      out.write("            <th>Tipo Usuário</th>\n");
      out.write("            <th colspan=\"2\">Ações</th>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        ");
 for (Usuario us : dados) { 
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( us.getId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( us.getNome() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( us.getTipoUsuarioId() );
      out.write("</td>\n");
      out.write("\n");
      out.write("            <td><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/usuarios_form.jsp?action=update&id=");
      out.print( us.getId() );
      out.write("\">Alterar</a></td>\n");
      out.write("\n");
      out.write("            <td>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home?action=delete&id=");
      out.print( us.getId() );
      out.write("&task=usuarios\"\n");
      out.write("                   onclick=\"return confirm('Deseja realmente excluir o usuário ");
      out.print( us.getNome() );
      out.write("?')\">\n");
      out.write("                   Excluir\n");
      out.write("                </a>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <br>\n");
      out.write("    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/usuarios_form.jsp?action=create\">Adicionar Usuário</a>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
