/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-12-10 02:13:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.app.atendimento;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Equipamento;
import java.util.ArrayList;
import model.Cliente;
import model.Usuario;
import model.TipoUsuario;

public final class equipamentos_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/home/app/modulos.jsp", Long.valueOf(1765330516573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("model.TipoUsuario");
    _jspx_imports_classes.add("model.Equipamento");
    _jspx_imports_classes.add("model.Usuario");
    _jspx_imports_classes.add("model.Cliente");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Equipamento</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    HttpSession s = request.getSession(false);

    Usuario usuarioLogado = null;
    TipoUsuario tipoUsuarioLogado = null;

    if (s != null) {
        usuarioLogado = (Usuario) s.getAttribute("usuario");
        tipoUsuarioLogado = (TipoUsuario) s.getAttribute("tipo_usuario");
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/menu.jsp\">Menu</a></li>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloAdmin())) { 
      out.write("\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/tipousuario.jsp\">Tipo Usuário</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/adm/usuarios.jsp\">Usuários</a></li>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloAtendimento())) { 
      out.write("\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/atendimento/clientes.jsp\">Clientes</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/atendimento/equipamentos.jsp\">Equipamentos</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/os/os.jsp\">Ordens de Serviço</a></li>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (tipoUsuarioLogado != null && "S".equals(tipoUsuarioLogado.getModuloTecnico())) { 
      out.write("\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/tecnico/tecnicos.jsp\">Técnicos</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home/app/os/os.jsp\">OS Técnicas</a></li>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home?task=logout\">\r\n");
      out.write("            Logout ");
      out.print( usuarioLogado != null ? usuarioLogado.getNome() : "" );
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            Equipamento eq = null;
            ArrayList<Cliente> clientesList = null;

            String action = request.getParameter("action");
            if (action == null) {
                action = "create";
            } else {
                if (action.equals("update")) {
                    int id = Integer.valueOf(request.getParameter("id"));

                    eq = new Equipamento();
                    eq.setId(id);
                    eq.load();
                }
            }

            // Verifica se já existe uma entidade nos atributos da requisição
            Equipamento entity = (Equipamento) request.getAttribute("entity");
            if (entity == null) {
                entity = eq != null ? eq : new Equipamento();
            }

            // Carrega lista de clientes
            clientesList = (ArrayList<Cliente>) request.getAttribute("clientesList");
            if (clientesList == null || clientesList.isEmpty()) {
                // Busca diretamente do modelo se não veio na requisição
                clientesList = new Cliente().getAllTableEntities();
            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h1>");
      out.print( entity.getId() == 0 ? "Novo Equipamento" : "Editar Equipamento" );
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath());
      out.write("/home?action=save&task=equipamentos\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("            <label for=\"id\">Id:</label>\r\n");
      out.write("            <input type=\"text\" id=\"id\" name=\"id\" pattern=\"\\d+\" title=\"apenas dígitos\" \r\n");
      out.write("                   value=\"");
      out.print( entity.getId() );
      out.write("\" \r\n");
      out.write("                   ");
      out.print( (entity.getId() != 0) ? "readonly" : "" );
      out.write(" required><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"clienteId\">Cliente:</label>\r\n");
      out.write("            <select id=\"clienteId\" name=\"clienteId\" required>\r\n");
      out.write("                <option value=\"\">-- selecione --</option>\r\n");
      out.write("                ");
 if (clientesList != null && !clientesList.isEmpty()) {
                    for (Cliente c : clientesList) { 
      out.write("\r\n");
      out.write("                <option value=\"");
      out.print( c.getId() );
      out.write("\"\r\n");
      out.write("                    ");
      out.print( (c.getId() == entity.getClienteId()) ? "selected" : "" );
      out.write(">\r\n");
      out.write("                    ");
      out.print( (c.getNome() != null) ? c.getNome() : "Cliente " + c.getId() );
      out.write("\r\n");
      out.write("                </option>\r\n");
      out.write("                ");
   }
                   } 
      out.write("\r\n");
      out.write("            </select><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"tipo\">Tipo:</label>\r\n");
      out.write("            <input type=\"text\" id=\"tipo\" name=\"tipo\" \r\n");
      out.write("                   value=\"");
      out.print( (entity.getTipo() != null) ? entity.getTipo() : "" );
      out.write("\" required><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"marca\">Marca:</label>\r\n");
      out.write("            <input type=\"text\" id=\"marca\" name=\"marca\" \r\n");
      out.write("                   value=\"");
      out.print( (entity.getMarca() != null) ? entity.getMarca() : "" );
      out.write("\"><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"modelo\">Modelo:</label>\r\n");
      out.write("            <input type=\"text\" id=\"modelo\" name=\"modelo\" \r\n");
      out.write("                   value=\"");
      out.print( (entity.getModelo() != null) ? entity.getModelo() : "" );
      out.write("\"><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"defeitoRelatado\">Defeito Relatado:</label><br/>\r\n");
      out.write("            <textarea id=\"defeitoRelatado\" name=\"defeitoRelatado\" rows=\"4\" cols=\"50\">\r\n");
      out.write("                ");
      out.print( (entity.getDefeitoRelatado() != null) ? entity.getDefeitoRelatado() : "" );
      out.write("\r\n");
      out.write("            </textarea><br/><br/>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\" name=\"Salvar\" value=\"Salvar\"> \r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home?task=equipamentos&action=list\">Cancelar</a>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
